on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

name: Build

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3

            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  cache: true

            - name: Install Dependencies
              run: flutter pub get

            - name: Build for IOS
              run: flutter build ios --release --no-codesign

            - name: Build for Web
              run: flutter build web
