on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

name: Build

jobs:
    build:
        name: Build App
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1

            - name: install dependencies
              uses: steebchen/flutter@v1.1.0
              with:
                  args: pub get

            - name: Build Web Project
              uses: steebchen/flutter@v1.1.0
              with:
                  args: build web

            - name: Build IOS Project
              uses: steebchen/flutter@v1.1.0
              with:
                  args: build ios
